version: '3.6'

services: 
    db:
      image: mysql
      container_name: full_db_mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
        start_period: 5s
        interval: 5s
        timeout: 5s
        retries: 55
      environment: 
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes: 
        - ./init:/docker-entrypoint-initdb.d
        - my-datavolume:/var/lib/mysql
      networks:
        - fullstack

    app:
      container_name: full_app
      build: .
      restart: on-failure
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_CONN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(full_db_mysql:3306)/${MYSQL_DATABASE}?charset=utf8&parseTime=True&loc=Local
      ports: 
        - 9090:9090 
      volumes:
        - .:/go/src/go-cake
      networks:
        - fullstack

    adminer:
      image: adminer
      restart: always
      ports: 
          - 8080:8080
    
    swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: swagger_ui_container
      ports:
          - "8081:8080"
      volumes:
          - ./doc:/usr/share/nginx/html/doc
      environment:
          API_URL: doc/openapi.yaml

networks:
  fullstack:
    driver: bridge

volumes:
  my-datavolume: